django_crm/clients/urls.py
from django.urls import path

from clients.views import (
    ClientActiveDeleteView,
    ClientActiveDetailsView,
    ClientActiveListView,
    ClientActiveUpdateView,
    ClientCreateView,
    ClientDeleteView,
    ClientDetailsView,
    ClientListView,
    ClientToActiveUpdateView,
    ClientUpdateView,
)

app_name = "clients"

urlpatterns = [
    path("", ClientListView.as_view(), name="client_list"),
    path("create/", ClientCreateView.as_view(), name="client_create"),
    path("<int:pk>/", ClientDetailsView.as_view(), name="client_details"),
    path("<int:pk>/update/", ClientUpdateView.as_view(), name="client_update"),
    path("<int:pk>/archived/", ClientDeleteView.as_view(), name="client_archived"),

    path("<int:pk>/client-to-active/", ClientToActiveUpdateView.as_view(), name="client_to_active"),

    path("active/", ClientActiveListView.as_view(), name="client_active_list"),
    path("active/<int:pk>/", ClientActiveDetailsView.as_view(), name="client_active_details"),
    path("active/<int:pk>/update/", ClientActiveUpdateView.as_view(), name="client_active_update"),
    path("active/<int:pk>/archived/", ClientActiveDeleteView.as_view(), name="client_active_archived"),
]

django_crm/django_crm/urls.py
from django.conf import settings

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from rest_framework.routers import DefaultRouter

from services.views import ServiceViewSet
from advertising_companies.views import AdvertisingCompanyViewSet
from clients.views import ClientViewSet, ClientActiveViewSet, ClientToActiveViewSet
from contracts.views import ContractViewSet

routers = DefaultRouter()
routers.register("services", ServiceViewSet, basename='services')
routers.register("advertising-companies", AdvertisingCompanyViewSet, basename='advertising_companies')
routers.register("clients", ClientViewSet, basename='clients')
routers.register("client-to-active", ClientToActiveViewSet, basename='client_to_active')
routers.register("client-active", ClientActiveViewSet, basename='client_active')
routers.register("contracts", ContractViewSet, basename='contracts')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authorization.urls')),
    path('statistics/', include('customer_statistics.urls')),
    path('services/', include('services.urls')),
    path('advertising-companies/', include('advertising_companies.urls')),
    path('clients/', include('clients.urls')),
    path('contracts/', include('contracts.urls')),

    path("api/", include(routers.urls)),
    path('api/', include('djoser.urls.authtoken')),
]

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls')),
    )

    urlpatterns += staticfiles_urlpatterns()

django_crm/clients/models.py
from django.db import models

from advertising_companies.models import AdvertisingCompany
from contracts.models import Contract


class Client(models.Model):
    class Meta:
        verbose_name = "Potential client"
        verbose_name_plural = "Potential clients"
        ordering = "id", "name"

    name = models.CharField(max_length=50, blank=False, unique=True)
    phone = models.CharField(max_length=10, blank=False)
    email = models.EmailField(blank=True)
    active = models.BooleanField(default=False)
    advertising_company = models.ForeignKey(AdvertisingCompany, on_delete=models.CASCADE, null=True)
    contract = models.ForeignKey(Contract, on_delete=models.CASCADE, null=True, default=None)

django_crm/clients/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import OrderingFilter, SearchFilter
from rest_framework import status, viewsets
from rest_framework.response import Response

from django.http import HttpResponseRedirect
from django.shortcuts import reverse
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from .models import Client
from .serializers import ClientSerializers, ClientActiveSerializers, ClientToActiveSerializer
from utils import HasRolePermission


ROLE_OPERATOR = "operator"
ROLE_MANAGER = "manager"


class ClientListView(UserPassesTestMixin, ListView):
    def test_func(self):
        user = self.request.user
        groups = set(str(group) for group in user.groups.all())
        if ROLE_OPERATOR in groups or user.is_staff:
            return True

    queryset = (
        Client.objects
        .prefetch_related("advertising_company")
        .filter(active=False)
    )


class ClientDetailsView(UserPassesTestMixin, DetailView):
    def test_func(self):
        user = self.request.user
        groups = set(str(group) for group in user.groups.all())
        if ROLE_OPERATOR in groups or user.is_staff:
            return True

    model = Client
    queryset = (
        Client.objects
        .prefetch_related("advertising_company")
        .all()
    )


class ClientCreateView(UserPassesTestMixin, CreateView):
    def test_func(self):
        user = self.request.user
        groups = set(str(group) for group in user.groups.all())
        if ROLE_OPERATOR in groups or user.is_staff:
            return True

    model = Client
    fields = "name", "phone", "email", "advertising_company",

    def get_success_url(self):
        return reverse(
            viewname="clients:client_details",
            kwargs={"pk": self.object.pk},
        )


class ClientUpdateView(UserPassesTestMixin, UpdateView):
    def test_func(self):
        user = self.request.user
        groups = set(str(group) for group in user.groups.all())
        if ROLE_OPERATOR in groups or user.is_staff:
            return True

    model = Client
    fields = "name", "phone", "email", "advertising_company",
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse(
            viewname="clients:client_details",
            kwargs={"pk": self.object.pk},
        )


class ClientDeleteView(UserPassesTestMixin, DeleteView):
    def test_func(self):
        user = self.request.user
        groups = set(str(group) for group in user.groups.all())
        if ROLE_OPERATOR in groups or user.is_staff:
            return True

    model = Client
    success_url = reverse_lazy("clients:client_list")


class ClientToActiveUpdateView(UserPassesTestMixin, UpdateView):
    def test_func(self):
        user = self.request.user
        groups = set(str(group) for group in user.groups.all())
        if ROLE_MANAGER in groups or user.is_staff:
            return True

    template_name = "clients/client_to_active.html"
    model = Client
    fields = "contract",
    success_url = reverse_lazy("clients:client_active_list")

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.active = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class ClientActiveListView(UserPassesTestMixin, ListView):
    def test_func(self):
        user = self.request.user
        groups = set(str(group) for group in user.groups.all())
        if ROLE_MANAGER in groups or user.is_staff:
            return True

    template_name = "clients/client_active_list.html"
    queryset = (
        Client.objects
        .prefetch_related("advertising_company")
        .filter(active=True)
    )


class ClientActiveDetailsView(UserPassesTestMixin, DetailView):
    def test_func(self):
        user = self.request.user
        groups = set(str(group) for group in user.groups.all())
        if ROLE_MANAGER in groups or user.is_staff:
            return True

    template_name = "clients/client_active_detail.html"
    model = Client

    queryset = (
        Client.objects
        .select_related("contract")
        .prefetch_related("advertising_company")
        .all()
    )


class ClientActiveUpdateView(UserPassesTestMixin, UpdateView):
    def test_func(self):
        user = self.request.user
        groups = set(str(group) for group in user.groups.all())
        if ROLE_MANAGER in groups or user.is_staff:
            return True

    template_name = "clients/client_active_update_form.html"
    model = Client
    fields = "name", "phone", "email", "contract", "advertising_company",

    def get_success_url(self):
        return reverse(
            viewname="clients:client_active_details",
            kwargs={"pk": self.object.pk},
        )


class ClientActiveDeleteView(UserPassesTestMixin, DeleteView):
    def test_func(self):
        user = self.request.user
        groups = set(str(group) for group in user.groups.all())
        if ROLE_MANAGER in groups or user.is_staff:
            return True

    template_name = "clients/client_confirm_active.html"
    model = Client
    success_url = reverse_lazy("clients:client_active_list")


class ClientViewSet(viewsets.ModelViewSet):
    permission_classes = (HasRolePermission("operator"),)
    queryset = Client.objects.filter(active=False)
    serializer_class = ClientSerializers
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]
    fields = [
        "name",
        "phone",
        "email",
        "advertising_company",
    ]

    search_fields = fields
    filterset_fields = fields
    ordering_fields = fields


class ClientActiveViewSet(viewsets.ModelViewSet):
    permission_classes = (HasRolePermission("manager"),)
    queryset = Client.objects.filter(active=True)
    serializer_class = ClientActiveSerializers
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]
    fields = [
        "name",
        "phone",
        "email",
        "advertising_company",
        "contract",
    ]

    search_fields = fields
    filterset_fields = fields
    ordering_fields = fields

    def create(self, request, *args, **kwargs):
        return Response({'error': 'Recording is prohibited'}, status=status.HTTP_403_FORBIDDEN)


class ClientToActiveViewSet(viewsets.ModelViewSet):
    permission_classes = (HasRolePermission("manager"),)
    queryset = Client.objects.filter(active=False)
    serializer_class = ClientToActiveSerializer
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]
    fields = [
        "name",
        "phone",
        "email",
        "advertising_company",
    ]

    search_fields = fields
    filterset_fields = fields
    ordering_fields = fields

    def create(self, request, *args, **kwargs):
        return Response({'error': 'The method is not available'}, status=status.HTTP_403_FORBIDDEN)

    def update(self, request, *args, **kwargs):
        partial = kwargs.pop('partial', False)
        instance = self.get_object()
        instance.active = True

        serializer = self.get_serializer(instance, data=request.data, partial=partial)
        serializer.is_valid(raise_exception=True)

        self.perform_update(serializer)

        if getattr(instance, '_prefetched_objects_cache', None):
            instance._prefetched_objects_cache = {}

        return Response(serializer.data)

    def destroy(self, request, *args, **kwargs):
        return Response({'error': 'The method is not available'}, status=status.HTTP_403_FORBIDDEN)

django_crm/clients/templates/clients/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

django_crm/clients/templates/clients/client_active_detail.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}
    {% translate 'Detail active client' %} #{{ object.pk }}
{% endblock %}

{% block name_page %}
    Detail active client
{% endblock %}

{% block body %}
    <div>
        {% translate 'Name: ' %} <strong>{{ object.name }}</strong>
        <p>{% translate 'Phone:' %} <em> {{ object.phone }}</em></p>
        <p>{% translate 'Email:' %} <em> {{ object.email }}</em></p>
        <p>{% translate 'Contract:' %} <em> {{ object.contract }}</em></p>
        <p>{% translate 'Advertising company:' %} <em> {{ object.advertising_company }}</em>
    </div>

    {% url 'clients:client_active_update' pk=object.pk as url_update_client %}
    {% url 'clients:client_active_archived' pk=object.pk as url_archive_client %}

    {% blocktranslate %}
        <div>
            <br>
            <a href="{{ url_update_client }}">
                <button class="button">Update</button>
            </a>
        </div>
        <div>
            <br>
            <a href="{{ url_archive_client }}">
                <button class="button button_red">Delete</button>
            </a>
        </div>
    {% endblocktranslate %}

    <div>
        {% url 'clients:client_active_list' as url_list_client %}
        {% blocktranslate %}
            <br>
            <a href="{{ url_list_client }}">
                <button class="button button_blue">Back</button>
            </a>
        {% endblocktranslate %}
    </div>
{% endblock %}

django_crm/clients/templates/clients/client_active_list.html
{% extends 'base.html' %}

{% block title %}
    Active clients
{% endblock %}

{% block name_page %}
    Active clients
{% endblock %}

{% block body %}
    <h3>List:</h3>
    <div>
        <ol>
            {% for client in object_list %}
                <li>
                    <div class="list_obj">
                        <div class="list_obj_name">
                            <a href="{% url 'clients:client_active_details' pk=client.pk %}">{{ client.name }}</a>
                        </div>
                        <div>
                            <a href="{% url 'clients:client_active_archived' pk=client.pk %}">
                                <button class="button button_red">Delete</button>
                            </a>
                        </div>
                    </div>
                </li>
            {% empty %} No clients yet
            {% endfor %}
        </ol>
    </div>

    <div>
        <br>
        <a href="{% url 'clients:client_list' %}">
            <button class="button button_blue">Client list</button>
        </a>
    </div>
{% endblock %}

django_crm/clients/templates/clients/client_active_update_form.html
{% extends 'base.html' %}

{% block title %}
    Update active client
{% endblock %}

{% block name_page %}
    Update active client
{% endblock %}

{% block body %}
    <h3>Enter the data:</h3>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <button type="submit" class="button">Update</button>
        </form>
    </div>
    <div>
        <br>
        <a href="{% url 'clients:client_active_details' pk=object.pk %}">
            <button class="button button_blue">Back</button>
        </a>
    </div>
{% endblock %}

django_crm/clients/templates/clients/client_confirm_active.html
{% extends 'base.html' %}

{% block title %}
    Confirm client to active {{ object.pk }}
{% endblock %}

{% block name_page %}
    Confirm client to active
{% endblock %}

{% block body %}
    <h3>Are you sure that the client "<i>{{ object.name }}</i>" is switching to active</h3>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <button type="submit" class="button">Sure</button>
        </form>
    </div>
    <br>
    <a href="{% url 'clients:client_active_list' %}">
        <button class="button button_blue">Back</button>
    </a>
{% endblock %}

django_crm/clients/templates/clients/client_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    Confirm delete {{ object.pk }}
{% endblock %}

{% block name_page %}
    Confirm
{% endblock %}

{% block body %}
    <h3>Are you sure you want to delete</h3>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <button type="submit" class="button button_red">Delete</button>
        </form>
    </div>
    <br>
    <a href="{% url 'clients:client_details' pk=object.pk %}">
        <button class="button button_blue">Back</button>
    </a>
{% endblock %}

django_crm/clients/templates/clients/client_detail.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}
    {% translate 'Detail client' %} #{{ object.pk }}
{% endblock %}

{% block name_page %}
    Detail client
{% endblock %}

{% block body %}
    <div>
        {% translate 'Name: ' %} <strong>{{ object.name }}</strong>
        <p>{% translate 'Phone:' %} <em> {{ object.phone }}</em></p>
        <p>{% translate 'Email:' %} <em> {{ object.email }}</em></p>
        <p>{% translate 'Advertising company:' %}
            <li><em> {{ object.advertising_company }} </em></li>
    </div>

    {% if user.is_superuser or perms.clients.change_client %}
        {% url 'clients:client_update' pk=object.pk as url_update_client %}
        {% url 'clients:client_archived' pk=object.pk as url_archive_client %}

        {% blocktranslate %}
            <div>
                <br>
                <a href="{{ url_update_client }}">
                    <button class="button">Update</button>
                </a>
            </div>
            <div>
                <br>
                <a href="{{ url_archive_client }}">
                    <button class="button button_red">Delete</button>
                </a>
            </div>
        {% endblocktranslate %}
    {% endif %}

    <div>
        {% url 'clients:client_list' as url_list_client %}
        {% blocktranslate %}
            <br>
            <a href="{{ url_list_client }}">
                <button class="button button_blue">Back</button>
            </a>
        {% endblocktranslate %}
    </div>
{% endblock %}

django_crm/clients/templates/clients/client_form.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Create client
{% endblock %}

{% block name_page %}
    Create client
{% endblock %}

{% block body %}
    <h3>Enter the data:</h3>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
        <button type="submit" class="button">Create</button>
        </form>
    </div>
    <div>
        <br>
        <a href="{% url 'clients:client_list' %}"><button class="button button_blue">Back</button></a>
    </div>
{% endblock %}

django_crm/clients/templates/clients/client_list.html
{% extends 'base.html' %}

{% block title %}
    Client list
{% endblock %}

{% block name_page %}
    Clients
{% endblock %}

{% block body %}
    <h3>List:</h3>
    <div>
        <ol>
            {% for client in object_list %}
                <li>
                    <div class="list_obj">
                        <div class="list_obj_name">
                            <a href="{% url 'clients:client_details' pk=client.pk %}">{{ client.name }}</a>
                        </div>

                        {% if perms.clients.to_active_client %}
                            <div>
                                <a href="{% url 'clients:client_to_active' pk=client.pk %}">
                                    <button class="button">To active</button>
                                </a>
                            </div>
                        {% endif %}

                        {% if perms.clients.delete_client %}
                            <div>
                                <a href="{% url 'clients:client_archived' pk=client.pk %}">
                                    <button class="button button_red">Delete</button>
                                </a>
                            </div>
                        {% endif %}

                    </div>
                </li>
            {% empty %} No clients yet
            {% endfor %}
        </ol>
    </div>

    {% if perms.clients.add_client %}
        <div>
            <br>
            <a href="{% url 'clients:client_create' %}">
                <button class="button">Create</button>
            </a>
        </div>
    {% endif %}

{% endblock %}

django_crm/clients/templates/clients/client_to_active.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}
    {% translate 'Client to active' %} #{{ object.pk }}
{% endblock %}

{% block name_page %}
    Client to active
{% endblock %}

{% block body %}
    <div>
        {% translate 'Name: ' %} <strong>{{ object.name }}</strong>
        <p>{% translate 'Phone:' %} <em> {{ object.phone }}</em></p>
        <p>{% translate 'Email:' %} <em> {{ object.email }}</em></p>
        <p>{% translate 'Advertising company:' %}
            <li><em> {{ object.advertising_company }} </em></li>

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <button type="submit" class="button">To active</button>
        </form>
    </div>

    <div>
        {% url 'clients:client_list' as url_list_client %}
        {% blocktranslate %}
            <br>
            <a href="{{ url_list_client }}">
                <button class="button button_blue">Back</button>
            </a>
        {% endblocktranslate %}
    </div>
{% endblock %}

django_crm/clients/templates/clients/client_update_form.html
{% extends 'base.html' %}

{% block title %}
    Update client
{% endblock %}

{% block name_page %}
    Update client
{% endblock %}

{% block body %}
    <h3>Enter the data:</h3>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <button type="submit" class="button">Update</button>
        </form>
    </div>
    <div>
        <br>
        <a href="{% url 'clients:client_details' pk=object.pk %}">
            <button class="button button_blue">Back</button>
        </a>
    </div>
{% endblock %}