django_crm/advertising_companies/urls.py
from django.urls import path

from .views import (
    AdvertisingCompaniesListView,
    AdvertisingCompanyCreateView,
    AdvertisingCompanyDeleteView,
    AdvertisingCompanyDetailsView,
    AdvertisingCompanyUpdateView,
    AdvertisingCompanyViewSet,
)

app_name = "advertising_companies"

urlpatterns = [
    path("", AdvertisingCompaniesListView.as_view(), name="advertising_companies_list"),
    path("create/", AdvertisingCompanyCreateView.as_view(), name="advertising_company_create"),
    path("<int:pk>/", AdvertisingCompanyDetailsView.as_view(), name="advertising_company_details"),
    path("<int:pk>/update/", AdvertisingCompanyUpdateView.as_view(), name="advertising_company_update"),
    path("<int:pk>/delete/", AdvertisingCompanyDeleteView.as_view(), name="advertising_company_archived"),
]

django_crm/clients/urls.py
from django.urls import path

from clients.views import (
    ClientActiveDeleteView,
    ClientActiveDetailsView,
    ClientActiveListView,
    ClientActiveUpdateView,
    ClientCreateView,
    ClientDeleteView,
    ClientDetailsView,
    ClientListView,
    ClientToActiveUpdateView,
    ClientUpdateView,
)

app_name = "clients"

urlpatterns = [
    path("", ClientListView.as_view(), name="client_list"),
    path("create/", ClientCreateView.as_view(), name="client_create"),
    path("<int:pk>/", ClientDetailsView.as_view(), name="client_details"),
    path("<int:pk>/update/", ClientUpdateView.as_view(), name="client_update"),
    path("<int:pk>/archived/", ClientDeleteView.as_view(), name="client_archived"),

    path("<int:pk>/client-to-active/", ClientToActiveUpdateView.as_view(), name="client_to_active"),

    path("active/", ClientActiveListView.as_view(), name="client_active_list"),
    path("active/<int:pk>/", ClientActiveDetailsView.as_view(), name="client_active_details"),
    path("active/<int:pk>/update/", ClientActiveUpdateView.as_view(), name="client_active_update"),
    path("active/<int:pk>/archived/", ClientActiveDeleteView.as_view(), name="client_active_archived"),
]

django_crm/django_crm/urls.py
from django.conf import settings

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from rest_framework.routers import DefaultRouter

from services.views import ServiceViewSet
from advertising_companies.views import AdvertisingCompanyViewSet
from clients.views import ClientViewSet, ClientActiveViewSet, ClientToActiveViewSet
from contracts.views import ContractViewSet

routers = DefaultRouter()
routers.register("services", ServiceViewSet, basename='services')
routers.register("advertising-companies", AdvertisingCompanyViewSet, basename='advertising_companies')
routers.register("clients", ClientViewSet, basename='clients')
routers.register("client-to-active", ClientToActiveViewSet, basename='client_to_active')
routers.register("client-active", ClientActiveViewSet, basename='client_active')
routers.register("contracts", ContractViewSet, basename='contracts')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authorization.urls')),
    path('statistics/', include('customer_statistics.urls')),
    path('services/', include('services.urls')),
    path('advertising-companies/', include('advertising_companies.urls')),
    path('clients/', include('clients.urls')),
    path('contracts/', include('contracts.urls')),

    path("api/", include(routers.urls)),
    path('api/', include('djoser.urls.authtoken')),
]

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls')),
    )

    urlpatterns += staticfiles_urlpatterns()

django_crm/advertising_companies/models.py
from django.db import models

from services.models import Service


class AdvertisingCompany(models.Model):
    class Meta:
        verbose_name = "Advertising company"
        verbose_name_plural = "Advertising companies"
        ordering = "id", "name"

    name = models.CharField(max_length=50, unique=True, blank=False)
    description = models.TextField(max_length=300, blank=True)
    promotion = models.CharField(max_length=50, blank=False)
    budget = models.DecimalField(max_digits=8, decimal_places=2, blank=False)
    services = models.ForeignKey(Service, on_delete=models.CASCADE)

    def __repr__(self):
        return (f"'id': {self.id}, 'name':{self.name}, 'budget': {self.budget}, 'services_price': {self.services.__repr__()}")

    def __str__(self):
        return self.name

django_crm/advertising_companies/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import OrderingFilter, SearchFilter
from rest_framework import viewsets
from django.shortcuts import reverse
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from .models import AdvertisingCompany
from .serializers import AdvertisingCompanySerializers
from utils import HasRolePermission


ROLE = "marketing"


class AdvertisingCompaniesListView(UserPassesTestMixin, ListView):
    def test_func(self):
        user = self.request.user
        groups = set(str(group) for group in user.groups.all())
        if ROLE in groups or user.is_staff:
            return True

    permission_required = "advertising_companies.view_advertisingcompany"
    template_name = "advertising_companies/advertising_companies_list.html"
    queryset = (
        AdvertisingCompany.objects
        .prefetch_related("services")
        .all()
    )


class AdvertisingCompanyDetailsView(UserPassesTestMixin, DetailView):
    def test_func(self):
        user = self.request.user
        groups = set(str(group) for group in user.groups.all())
        if ROLE in groups or user.is_staff:
            return True

    template_name = "advertising_companies/advertising_company_details.html"
    model = AdvertisingCompany
    queryset = (
        AdvertisingCompany.objects
        .prefetch_related("services")
        .all()
    )


class AdvertisingCompanyCreateView(UserPassesTestMixin, CreateView):
    def test_func(self):
        user = self.request.user
        groups = set(str(group) for group in user.groups.all())
        if ROLE in groups or user.is_staff:
            return True

    template_name = "advertising_companies/advertising_company_form.html"
    model = AdvertisingCompany
    fields = "name", "description",  "promotion", "services", "budget",
    success_url = reverse_lazy("advertising_companies:advertising_companies_list")


class AdvertisingCompanyUpdateView(UserPassesTestMixin, UpdateView):
    def test_func(self):
        user = self.request.user
        groups = set(str(group) for group in user.groups.all())
        if ROLE in groups or user.is_staff:
            return True

    template_name = "advertising_companies/advertising_company_update_form.html"
    model = AdvertisingCompany
    fields = "name", "description",  "promotion", "services", "budget",
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse(
            viewname="advertising_companies:advertising_company_details",
            kwargs={"pk": self.object.pk},
        )


class AdvertisingCompanyDeleteView(UserPassesTestMixin, DeleteView):
    def test_func(self):
        user = self.request.user
        groups = set(str(group) for group in user.groups.all())
        if ROLE in groups or user.is_staff:
            return True

    template_name = "advertising_companies/advertising_company_confirm_delete.html"
    model = AdvertisingCompany
    success_url = reverse_lazy("advertising_companies:advertising_companies_list")


class AdvertisingCompanyViewSet(viewsets.ModelViewSet):
    permission_classes = (HasRolePermission("marketing"),)
    queryset = AdvertisingCompany.objects.all()
    serializer_class = AdvertisingCompanySerializers
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]

    fields = [
        "name",
        "description",
        "promotion",
        "budget",
        "services",
    ]

    search_fields = fields
    filterset_fields = fields
    ordering_fields = fields

django_crm/advertising_companies/templates/advertising_companies/advertising_companies_list.html
{% extends 'base.html' %}

{% block title %}
    Advertising companies list
{% endblock %}

{% block name_page %}
    Advertising companies
{% endblock %}

{% block body %}
    <h3>List:</h3>
    <div>
        <ol>
            {% for advertising_company in object_list %}
                <li>
                    <div class="list_obj">
                        <div class="list_obj_name">
                            <a href="{% url 'advertising_companies:advertising_company_details' pk=advertising_company.pk %}">{{ advertising_company.name }}</a>
                        </div>
                        <div>
                            <a href="{% url 'advertising_companies:advertising_company_archived' pk=advertising_company.pk %}">
                                <button class="button button_red">Delete</button>
                            </a>
                        </div>
                    </div>
                </li>
            {% empty %} No advertising companies yet
            {% endfor %}
        </ol>
    </div>

    <div>
        <br>
        <a href="{% url 'advertising_companies:advertising_company_create' %}">
            <button class="button">Create</button>
        </a>
    </div>
{% endblock %}

django_crm/advertising_companies/templates/advertising_companies/advertising_company_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    Confirm delete {{ object.pk }}
{% endblock %}

{% block name_page %}
    Confirm
{% endblock %}

{% block body %}
    <h3>Are you sure you want to delete</h3>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <button type="submit" class="button button_red">Delete</button>
        </form>
    </div>
    <br>
    <a href="{% url 'advertising_companies:advertising_company_details' pk=object.pk %}">
        <button class="button button_blue">Back</button>
    </a>
{% endblock %}

django_crm/advertising_companies/templates/advertising_companies/advertising_company_details.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}
    {% translate 'Detail advertising company' %} #{{ object.pk }}
{% endblock %}

{% block name_page %}
    Detail advertising company
{% endblock %}

{% block body %}
    <div>
        {% translate 'Name: ' %} <strong>{{ object.name }}</strong>
        <p>{% translate 'Description:' %} <em> {{ object.description }}</em></p>
        <p>{% translate 'Promotion:' %} <em> {{ object.promotion }}</em></p>
        <p>{% translate 'Budget:' %} <em> {% firstof object.budget 0 %} </em></p>
        Services in advertising company:
        <ol>
            {% for services in object.services.all %}
                <li><p>Name: {{ services.name }}, price: {{ services.price }}</p></li>
            {% endfor %}
        </ol>
    </div>

    {% url 'advertising_companies:advertising_company_update' pk=object.pk as url_update_advertising_company %}
    {% url 'advertising_companies:advertising_company_archived' pk=object.pk as url_archive_advertising_company %}

    {% blocktranslate %}
        <div>
            <br>
            <a href="{{ url_update_advertising_company }}">
                <button class="button">Update</button>
            </a>
        </div>
        <div>
            <br>
            <a href="{{ url_archive_advertising_company }}">
                <button class="button button_red">Delete</button>
            </a>
        </div>
    {% endblocktranslate %}

    <div>
        {% url 'advertising_companies:advertising_companies_list' as url_list_service %}
        {% blocktranslate %}
            <br>
            <a href="{{ url_list_service }}">
                <button class="button button_blue">Back</button>
            </a>
        {% endblocktranslate %}
    </div>
{% endblock %}

django_crm/advertising_companies/templates/advertising_companies/advertising_company_form.html
{% extends 'base.html' %}

{% block title %}
    Create advertising company
{% endblock %}

{% block name_page %}
    Create advertising company
{% endblock %}

{% block body %}
    <h3>Enter the data:</h3>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
        <button type="submit" class="button">Create</button>
        </form>
    </div>
    <div>
        <br>
        <a href="{% url 'advertising_companies:advertising_companies_list' %}"><button class="button button_blue">Back</button></a>
    </div>
{% endblock %}

django_crm/advertising_companies/templates/advertising_companies/advertising_company_update_form.html
{% extends 'base.html' %}

{% block title %}
    Update advertising company
{% endblock %}

{% block name_page %}
    Update advertising company
{% endblock %}

{% block body %}
    <h3>Enter the data:</h3>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <button type="submit" class="button">Update</button>
        </form>
    </div>
    <div>
        <br>
        <a href="{% url 'advertising_companies:advertising_company_details' pk=object.pk %}">
            <button class="button button_blue">Back</button>
        </a>
    </div>
{% endblock %}

django_crm/advertising_companies/templates/advertising_companies/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>