django_crm/authorization/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from .views import LogoutView

app_name = "authorization"

urlpatterns = [
    path(
        "",
        LoginView.as_view(
            template_name='authorization/login.html',
            redirect_authenticated_user=True,
        ),
        name="login"
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
]

django_crm/clients/urls.py
from django.urls import path

from clients.views import (
    ClientActiveDeleteView,
    ClientActiveDetailsView,
    ClientActiveListView,
    ClientActiveUpdateView,
    ClientCreateView,
    ClientDeleteView,
    ClientDetailsView,
    ClientListView,
    ClientToActiveUpdateView,
    ClientUpdateView,
)

app_name = "clients"

urlpatterns = [
    path("", ClientListView.as_view(), name="client_list"),
    path("create/", ClientCreateView.as_view(), name="client_create"),
    path("<int:pk>/", ClientDetailsView.as_view(), name="client_details"),
    path("<int:pk>/update/", ClientUpdateView.as_view(), name="client_update"),
    path("<int:pk>/archived/", ClientDeleteView.as_view(), name="client_archived"),

    path("<int:pk>/client-to-active/", ClientToActiveUpdateView.as_view(), name="client_to_active"),

    path("active/", ClientActiveListView.as_view(), name="client_active_list"),
    path("active/<int:pk>/", ClientActiveDetailsView.as_view(), name="client_active_details"),
    path("active/<int:pk>/update/", ClientActiveUpdateView.as_view(), name="client_active_update"),
    path("active/<int:pk>/archived/", ClientActiveDeleteView.as_view(), name="client_active_archived"),
]

django_crm/contracts/urls.py
from django.urls import path

from .views import (
    ContractCreateView,
    ContractDeleteView,
    ContractDetailsView,
    ContractListView,
    ContractUpdateView,
)

app_name = "contracts"

urlpatterns = [
    path("", ContractListView.as_view(), name="contract_list"),
    path("create/", ContractCreateView.as_view(), name="contract_create"),
    path("<int:pk>/", ContractDetailsView.as_view(), name="contract_details"),
    path("<int:pk>/update/", ContractUpdateView.as_view(), name="contract_update"),
    path("<int:pk>/delete/", ContractDeleteView.as_view(), name="contract_archived"),
]

django_crm/customer_statistics/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from django_crm.settings import CACHE_SECONDS

from .views import CustomerStatistics

app_name = "customer_statistics"

urlpatterns = [
    path("", cache_page(CACHE_SECONDS)(CustomerStatistics.as_view()), name="statistics"),
]

django_crm/django_crm/urls.py
from django.conf import settings

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from rest_framework.routers import DefaultRouter

from services.views import ServiceViewSet
from advertising_companies.views import AdvertisingCompanyViewSet
from clients.views import ClientViewSet, ClientActiveViewSet, ClientToActiveViewSet
from contracts.views import ContractViewSet

routers = DefaultRouter()
routers.register("services", ServiceViewSet, basename='services')
routers.register("advertising-companies", AdvertisingCompanyViewSet, basename='advertising_companies')
routers.register("clients", ClientViewSet, basename='clients')
routers.register("client-to-active", ClientToActiveViewSet, basename='client_to_active')
routers.register("client-active", ClientActiveViewSet, basename='client_active')
routers.register("contracts", ContractViewSet, basename='contracts')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authorization.urls')),
    path('statistics/', include('customer_statistics.urls')),
    path('services/', include('services.urls')),
    path('advertising-companies/', include('advertising_companies.urls')),
    path('clients/', include('clients.urls')),
    path('contracts/', include('contracts.urls')),

    path("api/", include(routers.urls)),
    path('api/', include('djoser.urls.authtoken')),
]

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls')),
    )

    urlpatterns += staticfiles_urlpatterns()

django_crm/services/urls.py
from django.urls import path

from .views import (
    ServiceCreateView,
    ServiceDeleteView,
    ServiceDetailsView,
    ServicesListView,
    ServiceUpdateView,
)

app_name = "services"

urlpatterns = [
    path("", ServicesListView.as_view(), name="service_list"),
    path("create/", ServiceCreateView.as_view(), name="service_create"),
    path("<int:pk>/", ServiceDetailsView.as_view(), name="service_details"),
    path("<int:pk>/update/", ServiceUpdateView.as_view(), name="service_update"),
    path("<int:pk>/delete/", ServiceDeleteView.as_view(), name="service_archived"),
]

django_crm/django_crm/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"/>
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>

<header class="header">
    {% if user.is_authenticated %}
        <div class="logout">
            <a href={% url 'authorization:logout' %}>
                <button class="button button_gray">Logout</button>
            </a>
        </div>
        <div class="user_name">
            <p>
                {% if user.first_name or user.last_name %}
                    {{ user.first_name }} {{ user.last_name }}
                {% else %}
                    {{ user.username }}
                {% endif %}
            </p>
        </div>
    {% endif %}
    <div class="name_app"><p>CRM system advertising services</p></div>
</header>

<body>
<div class="workspace">
    <div class="menu_nav menu">
        {% if user.is_authenticated %}
            <div>
                <a href={% url 'customer_statistics:statistics' %}>
                    <span><i class="fas fa-newspaper"></i> Statistics</span>
                </a>
            </div>
            {% if user.is_superuser or perms.services.view_service %}
                <br>
                <div>
                    <a href={% url 'services:service_list' %}>
                        <span><i class="fas fa-microchip"></i> Services</span>
                    </a>
                </div>
            {% endif %}

            {% if user.is_superuser or perms.advertising_companies.view_advertisingcompany %}
                <br>
                <div>
                    <a href={% url 'advertising_companies:advertising_companies_list' %}>
                        <span><i class="fas fa-ad"></i> Advertisement</span>
                    </a>
                </div>
            {% endif %}

            {% if user.is_superuser or perms.clients.view_client %}
                <br>
                <div>
                    <a href={% url 'clients:client_list' %}>
                        <span><i class="fas fa-user-clock"></i> Clients</span>
                    </a>
                </div>
            {% endif %}

            {% if user.is_superuser or perms.clients.view_active_client %}
                <br>
                <div>
                    <a href={% url 'clients:client_active_list' %}>
                        <span><i class="fas fa-user-check"></i> Active clients</span>
                    </a>
                </div>
            {% endif %}

            {% if user.is_superuser or perms.contracts.view_contract %}
                <br>
                <div>
                    <a href={% url 'contracts:contract_list' %}>
                        <span><i class="fas fa-file-alt"></i> Contracts</span>
                    </a>
                </div>
            {% endif %}
        {% endif %}
    </div>

    <div class="group_Npage_Oinfo">
        <div class="name_page">
            <p>
                {% block name_page %}
                {% endblock %}
            </p>
        </div>
        <div class="output_info">
            {% block body %}
            {% endblock %}
        </div>
    </div>

</div>

<footer>
    <div class="def_year">
        @2024
    </div>
</footer>

</body>
</html>