django_crm/clients/urls.py
from django.urls import path

from clients.views import (
    ClientActiveDeleteView,
    ClientActiveDetailsView,
    ClientActiveListView,
    ClientActiveUpdateView,
    ClientCreateView,
    ClientDeleteView,
    ClientDetailsView,
    ClientListView,
    ClientToActiveUpdateView,
    ClientUpdateView,
)

app_name = "clients"

urlpatterns = [
    path("", ClientListView.as_view(), name="client_list"),
    path("create/", ClientCreateView.as_view(), name="client_create"),
    path("<int:pk>/", ClientDetailsView.as_view(), name="client_details"),
    path("<int:pk>/update/", ClientUpdateView.as_view(), name="client_update"),
    path("<int:pk>/archived/", ClientDeleteView.as_view(), name="client_archived"),

    path("<int:pk>/client-to-active/", ClientToActiveUpdateView.as_view(), name="client_to_active"),

    path("active/", ClientActiveListView.as_view(), name="client_active_list"),
    path("active/<int:pk>/", ClientActiveDetailsView.as_view(), name="client_active_details"),
    path("active/<int:pk>/update/", ClientActiveUpdateView.as_view(), name="client_active_update"),
    path("active/<int:pk>/archived/", ClientActiveDeleteView.as_view(), name="client_active_archived"),
]

django_crm/contracts/urls.py
from django.urls import path

from .views import (
    ContractCreateView,
    ContractDeleteView,
    ContractDetailsView,
    ContractListView,
    ContractUpdateView,
)

app_name = "contracts"

urlpatterns = [
    path("", ContractListView.as_view(), name="contract_list"),
    path("create/", ContractCreateView.as_view(), name="contract_create"),
    path("<int:pk>/", ContractDetailsView.as_view(), name="contract_details"),
    path("<int:pk>/update/", ContractUpdateView.as_view(), name="contract_update"),
    path("<int:pk>/delete/", ContractDeleteView.as_view(), name="contract_archived"),
]

django_crm/django_crm/urls.py
from django.conf import settings

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from rest_framework.routers import DefaultRouter

from services.views import ServiceViewSet
from advertising_companies.views import AdvertisingCompanyViewSet
from clients.views import ClientViewSet, ClientActiveViewSet, ClientToActiveViewSet
from contracts.views import ContractViewSet

routers = DefaultRouter()
routers.register("services", ServiceViewSet, basename='services')
routers.register("advertising-companies", AdvertisingCompanyViewSet, basename='advertising_companies')
routers.register("clients", ClientViewSet, basename='clients')
routers.register("client-to-active", ClientToActiveViewSet, basename='client_to_active')
routers.register("client-active", ClientActiveViewSet, basename='client_active')
routers.register("contracts", ContractViewSet, basename='contracts')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authorization.urls')),
    path('statistics/', include('customer_statistics.urls')),
    path('services/', include('services.urls')),
    path('advertising-companies/', include('advertising_companies.urls')),
    path('clients/', include('clients.urls')),
    path('contracts/', include('contracts.urls')),

    path("api/", include(routers.urls)),
    path('api/', include('djoser.urls.authtoken')),
]

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls')),
    )

    urlpatterns += staticfiles_urlpatterns()

django_crm/contracts/models.py
from django.db import models

from services.models import Service


class Contract(models.Model):
    class Meta:
        verbose_name = "Contract"
        verbose_name_plural = "Contracts"
        ordering = "id", "name"

    name = models.CharField(max_length=50, blank=False, unique=True)
    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name="names")
    document_file = models.FileField(blank=True, null=True, upload_to='contracts/contracts/')
    date_conclusion = models.DateTimeField()
    period_validity = models.CharField(max_length=50, blank=False)
    amount = models.DecimalField(max_digits=8, decimal_places=2, blank=False)

    def __repr__(self):
        return {f"'amount': {self.amount}"}

    def __str__(self):
        return self.name

django_crm/contracts/forms.py
from django import forms
from django.forms import ModelForm

from .models import Contract


class DateInput(forms.DateInput):
    input_type = 'date'


class ContractForm(ModelForm):

    class Meta:
        model = Contract
        fields = "name", "service", "document_file", "date_conclusion", "period_validity", "amount",
        widgets = {
            'date_conclusion': DateInput(),
        }

django_crm/contracts/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import OrderingFilter, SearchFilter
from rest_framework import viewsets
from django.shortcuts import reverse
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from .forms import ContractForm
from .models import Contract
from .serializers import ContractSerializers
from utils import HasRolePermission


ROLE = "manager"


class ContractListView(UserPassesTestMixin, ListView):
    def test_func(self):
        user = self.request.user
        groups = set(str(group) for group in user.groups.all())
        if ROLE in groups or user.is_staff:
            return True

    queryset = Contract.objects.all()


class ContractDetailsView(UserPassesTestMixin, DetailView):
    def test_func(self):
        user = self.request.user
        groups = set(str(group) for group in user.groups.all())
        if ROLE in groups or user.is_staff:
            return True

    permission_required = "contracts.view_contract"
    model = Contract
    queryset = Contract.objects.all()


class ContractCreateView(UserPassesTestMixin, CreateView):
    def test_func(self):
        user = self.request.user
        groups = set(str(group) for group in user.groups.all())
        if ROLE in groups or user.is_staff:
            return True

    model = Contract
    form_class = ContractForm
    success_url = reverse_lazy("contracts:contract_list")

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        response = super().form_valid(form)
        return response


class ContractUpdateView(UserPassesTestMixin, UpdateView):
    def test_func(self):
        user = self.request.user
        groups = set(str(group) for group in user.groups.all())
        if ROLE in groups or user.is_staff:
            return True

    model = Contract
    form_class = ContractForm
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse(
            viewname="contracts:contract_details",
            kwargs={"pk": self.object.pk},
        )


class ContractDeleteView(UserPassesTestMixin, DeleteView):
    def test_func(self):
        user = self.request.user
        groups = set(str(group) for group in user.groups.all())
        if ROLE in groups or user.is_staff:
            return True

    model = Contract
    success_url = reverse_lazy("contracts:contract_list")


class ContractViewSet(viewsets.ModelViewSet):
    permission_classes = (HasRolePermission("manager"),)
    queryset = Contract.objects.all()
    serializer_class = ContractSerializers
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]

    fields = [
        "name",
        "service",
        "date_conclusion",
        "period_validity",
        "amount",
    ]

    search_fields = fields
    filterset_fields = fields
    ordering_fields = fields

django_crm/contracts/templates/contracts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

django_crm/contracts/templates/contracts/contract_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    Confirm delete {{ object.pk }}
{% endblock %}

{% block name_page %}
    Confirm
{% endblock %}

{% block body %}
    <h3>Are you sure you want to delete</h3>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="button button_red">Delete</button>
        </form>
    </div>
    <br>
    <a href="{% url 'contracts:contract_details' pk=object.pk %}">
        <button class="button button_blue">Back</button>
    </a>
{% endblock %}

django_crm/contracts/templates/contracts/contract_detail.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}
    {% translate 'Detail contract' %} #{{ object.pk }}
{% endblock %}

{% block name_page %}
    Detail contract
{% endblock %}

{% block body %}
    <div>
        {% translate 'Name: ' %} <strong>{{ object.name }}</strong>
        <p>{% translate 'Service:' %} <em> {{ object.service }}</em></p>
        <p>{% translate 'Document file:' %} <em> {{ object.document_file }} </em></p>
        <p>{% translate 'Date conclusion:' %}
            <em> {{ object.date_conclusion.day }}.{{ object.date_conclusion.month }}.{{ object.date_conclusion.year }} </em>
        </p>
        <p>{% translate 'Period validity:' %} <em> {{ object.period_validity }} </em></p>
        <p>{% translate 'Amount:' %} <em> {{ object.amount }} </em></p>
    </div>

    {% url 'contracts:contract_update' pk=contract.pk as url_update_contract %}
    {% url 'contracts:contract_archived' pk=contract.pk as url_archive_contract %}

    {% blocktranslate %}
        <br>
        <div>
            <a href="{{ url_update_contract }}">
                <button class="button">Update</button>
            </a>
        </div>
        <br>
        <div>
            <a href="{{ url_archive_contract }}">
                <button class="button button_red">Delete</button>
            </a>
        </div>
    {% endblocktranslate %}

    <br>
    <div>
        {% url 'contracts:contract_list' as url_list_contract %}
        {% blocktranslate %}
            <a href="{{ url_list_contract }}">
                <button class="button button_blue">Back</button>
            </a>
        {% endblocktranslate %}
    </div>
{% endblock %}

django_crm/contracts/templates/contracts/contract_form.html
{% extends 'base.html' %}

{% block title %}
    Create contract
{% endblock %}

{% block name_page %}
    Create contract
{% endblock %}

{% block body %}
    <h3>Enter the data:</h3>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <button type="submit" class="button">Create</button>
        </form>
    </div>
    <div>
        <br>
        <a href="{% url 'contracts:contract_list' %}">
            <button class="button button_blue">Back</button>
        </a>
    </div>
{% endblock %}

django_crm/contracts/templates/contracts/contract_list.html
{% extends 'base.html' %}

{% block title %}
    Contract-list
{% endblock %}

{% block name_page %}
    Contracts
{% endblock %}

{% block body %}
    <h3>List:</h3>
    <div>
        <ol>
            {% for contract in object_list %}
                <li>
                    <div class="list_obj">
                        <div class="list_obj_name">
                            <a href="{% url 'contracts:contract_details' pk=contract.pk %}">{{ contract.name }}</a>
                        </div>
                        <div>
                            <a href="{% url 'contracts:contract_archived' pk=contract.pk %}">
                                <button class="button button_red">Delete</button>
                            </a>
                        </div>
                    </div>
                </li>
            {% empty %} No contracts yet
            {% endfor %}
        </ol>
    </div>

    <div>
        <br>
        <a href="{% url 'contracts:contract_create' %}">
            <button class="button">Create</button>
        </a>
    </div>

{% endblock %}

django_crm/contracts/templates/contracts/contract_update_form.html
{% extends 'base.html' %}

{% block title %}
    Update contract
{% endblock %}

{% block name_page %}
    Update contract
{% endblock %}

{% block body %}
    <h3>Enter the data:</h3>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <button type="submit" class="button">Update</button>
        </form>
    </div>
    <div>
        <br>
        <a href="{% url 'contracts:contract_details' pk=object.pk %}">
            <button class="button button_blue">Back</button>
        </a>
    </div>
{% endblock %}